# Generated by Django 2.2.5 on 2020-03-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200324_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.TextField(max_length=120),
        ),
    ]
