# Generated by Django 2.2.5 on 2020-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200324_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
