# Generated by Django 2.2.5 on 2019-09-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=50)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
