# Generated by Django 2.2.5 on 2019-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='newprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
