# Generated by Django 2.2.5 on 2019-10-08 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_remove_destination_newprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
