# Generated by Django 2.2.5 on 2019-10-10 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
    ]
