# Generated by Django 3.1.4 on 2021-01-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210118_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourites',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
