# Generated by Django 3.1.4 on 2021-01-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210118_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favourites',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='accounts.Favourite'),
        ),
    ]
